### ISSUE TITLE
AcceptAsync inside/outside while loop

### ISSUE THREAD

**Issue by cirrusone** [StephenClearyExamples/TcpChat#2]
Hi Stephen,

Firstly, thank you for the Asynchronous TCP/IP videos, they have been really useful and contain lots of really useful background info.

In your file .../TcpChat/Chat/ChatServer/Program.cs you have `AcceptAsync` inside the while loop, eg

```
while (true)
{
    var connectedSocket = await listeningSocket.AcceptAsync();

    // Receive message.
    // ...
}
```

In Microsoft's docs [create-a-socket-server](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/sockets/socket-services#create-a-socket-server) `AcceptAsync` is before the while loop, eg

```
var handler = await listener.AcceptAsync();
while (true)
{
    // Receive message.
    // ...
}
```

I just wanted to know if there were valid reasons for doing one over the other? Does the Microsoft example only listen for and allow a single connection but your sample listens for multiple connections or are there other things to consider?

Many thanks,
R

**Comment by fredimachado** [comment]
Hey, I will take the liberty to respond and point out that you figured this out already.
The MS example is only accepting a single connection while Stephen's server accepts multiple.

**Comment by cirrusone** [comment]
Excellent, thank you.
